name: Linux x64

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt install libmysqlclient-dev libmysqlcppconn-dev openssl
    - name: Setup Project
      run: ./setup.sh
    - name: Compile Project
      run: make
